# Generated by Django 4.1 on 2026-01-23 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_department_alter_hello_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hello',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.department'),
        ),
    ]
