# Generated by Django 6.0 on 2025-12-24 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_department_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='department',
        ),
    ]
