# Generated by Django 6.0 on 2025-12-24 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student',
            new_name='stu',
        ),
    ]
