# Generated by Django 6.0 on 2025-12-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_student_stu'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
