# Generated by Django 6.0 on 2025-12-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_stu_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu',
            name='branch',
            field=models.CharField(default='/0', max_length=1),
            preserve_default=False,
        ),
    ]
